plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - pkgRoot: dist
  - - "@semantic-release/exec"
    - prepareCmd: "yarn build"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - README.md
        - dist/**
      message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
